/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonLayout: typeof import('./src/components/commonLayout.vue')['default']
    CustomIcon: typeof import('./src/components/customIcon.vue')['default']
    PrettyCheckBox: typeof import('./src/components/prettyCheckBox.vue')['default']
    PrettyNavBar: typeof import('./src/components/prettyNavBar.vue')['default']
    ProductCard: typeof import('./src/components/productCard.vue')['default']
    RecommendCaseCard: typeof import('./src/components/recommendCaseCard.vue')['default']
    RecommendProductCard: typeof import('./src/components/recommendProductCard.vue')['default']
    SearchInput: typeof import('./src/components/searchInput.vue')['default']
    WdBadge: typeof import('wot-design-uni/components/wd-badge/wd-badge.vue')['default']
    WdCheckbox: typeof import('wot-design-uni/components/wd-checkbox/wd-checkbox.vue')['default']
    WdConfigProvider: typeof import('wot-design-uni/components/wd-config-provider/wd-config-provider.vue')['default']
    WdImg: typeof import('wot-design-uni/components/wd-img/wd-img.vue')['default']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
    WdNavbar: typeof import('wot-design-uni/components/wd-navbar/wd-navbar.vue')['default']
    WdStatusTip: typeof import('wot-design-uni/components/wd-status-tip/wd-status-tip.vue')['default']
    WdSwiper: typeof import('wot-design-uni/components/wd-swiper/wd-swiper.vue')['default']
    WdTab: typeof import('wot-design-uni/components/wd-tab/wd-tab.vue')['default']
    WdTabs: typeof import('wot-design-uni/components/wd-tabs/wd-tabs.vue')['default']
  }
}
