/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonLayout: typeof import('./components/commonLayout.vue')['default']
    CustomIcon: typeof import('./components/customIcon.vue')['default']
    PrettyCheckBox: typeof import('./components/prettyCheckBox.vue')['default']
    PrettyNavBar: typeof import('./components/prettyNavBar.vue')['default']
    ProductCard: typeof import('./components/productCard.vue')['default']
    RecommendCaseCard: typeof import('./components/recommendCaseCard.vue')['default']
    RecommendProductCard: typeof import('./components/recommendProductCard.vue')['default']
    SearchInput: typeof import('./components/searchInput.vue')['default']
  }
}
