/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/tabbar/index" |
       "/pages/caseDetail" |
       "/pages/login" |
       "/pages/myFavorites" |
       "/pages/myHistory" |
       "/pages/privacy" |
       "/pages/productDetail" |
       "/pages/productList" |
       "/pages/productSearch" |
       "/pages/tabbar/logo" |
       "/pages/tabbar/mine" |
       "/pages/tabbar/prod";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/tabbar/index" | "/pages/tabbar/prod" | "/pages/tabbar/logo" | "/pages/tabbar/mine"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
